language: julia
os: linux

julia: 
    - release
    - nightly

notifications: 
    email: false

git: 
    depth: false

script:
    - apt-get install -y hdf5-tools
    - julia -e 'import Pkg; Pkg.add("HDF5")'
    - julia -e 'import Pkg; Pkg.clone(pwd()); Pkg.test("RealNeuralNetworks")'
