language: julia
os: linux

julia: 
    - 0.7
    - nightly

notifications: 
    email: false


script:
    - julia -e 'import Pkg; Pkg.clone("https://github.com/seung-lab/BigArrays.jl.git")'
    - julia -e 'import Pkg; Pkg.clone(pwd()); Pkg.test("RealNeuralNetworks")'
    - julia -e 'using Pkg; Pkg.add("Documenter")'
    - julia -e 'using Pkg; cd(Pkg.dir("RealNeuralNetworks")); include(joinpath("docs", "make.jl"))'


matrix:
    allow_failures:
        - julia: nightly
