language: julia
os: linux

julia: 
    - release
    - nightly

notifications: 
    email: false

git: 
    depth: 99999

script:
    - julia -e 'Pkg.add("HDF5")'
    - julia -e 'Pkg.clone(pwd()); Pkg.test("RealNeuralNetworks")'
